services:
  - type: web
    name: predictive-maintenance-api
    runtime: docker
    plan: starter # Starter plan is required to use persistent disks
    envVars:
      - key: PORT
        value: 8000
    disk:
      name: database-storage
      mountPath: /app/database
      sizeGB: 1

  - type: web
    name: predictive-maintenance-frontend
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile.frontend
    envVars:
      - key: PORT
        value: 8501
      - key: API_BASE_URL
        value: https://ai-based-predictive-maintenance-system-1.onrender.com

